M1zz/RelaxOn

- LullabyRecipe/Model/DummyData.swift
- LullabyRecipe/Model/MixedSound.swift
1. File : VolumeControl.swift
baseSound, melodySound, naturalSound의 값을 변경해서 에러가 발생합니다. 
MixedSound의 해당 프로퍼티들을 let -> var로 변경했습니다.
2. File : DummyData.swift
enum (BaseAudioName) case가 아닌 거에 접근을 해서 에러가 발생합니다. 
dummyBaseSound, dummyMelodySound, dummyNaturalSound의 name을 바꿨습니다.
Issues: #28
> [Bug]: #28 develop branch build시 error 발생

- LullabyRecipe/Views/CustomTabView.swift
리팩토링하다가 발견한 오류로, "Color("Forground")"라고 하드 코딩이 되어있었습니다. 
Static에서 정의했던 enum을 이용한 ColorPalette.forground.color 로 변경했습니다.
Close #77
> [Fix]: #77 color name 변경

- LullabyRecipe.xcodeproj/project.pbxproj
- LullabyRecipe/Manager/AudioManager.swift
- LullabyRecipe/Model/Sound.swift
- LullabyRecipe/Views/Home/MixedSoundCardView.swift
- LullabyRecipe/Views/Home/Music/MusicView.swift
- LullabyRecipe/Views/Home/Music/VolumeControlView.swift
- LullabyRecipe/Views/Kitchen/CustomAlertView.swift
- forced unwrapping 제거했습니다.
- confirmationdialog에서 title이 뜨지 않는 현상 수정
- Audiomanager에 있던 오타 수정 (chanegeVolume() -> changeVolume())
- musicView의 forcedunwrapping을 해결하기 위해 두 가지 방법을 생각했었습니다.
1.
```
if let baseSound = data.baseSound,
let melodySound = data.melodySound,
let naturalSound = data.naturalSound {
ZStack(alignment: .top) {
ColorPalette.background.color.ignoresSafeArea()
VStack {
MusicInfo()
Divider()
VStack(spacing: 20) {
Divider()
.background(.white)
.padding(.horizontal, 20)
SingleSong(song: baseSound)
...code...
}
}
```
2.
```
SingleSong(song: data.baseSound ?? baseSounds[0])
```
위 두 가지 방법을 가지고 고민을 하고 있었는데 if let과 같은 unwrapping 요소가 view안에 들어가는 것은 저희가 지향하려 하는 MVVM 패턴에 맞지 않기 때문에 2번 방법을 택했습니다. 그런데 2번 방법에서도 baseSounds[0]을 봤을 때 
```
Sound(id: 0,
name: "Empty",
soundType: .base, …
```
> [Feat] forced unwrapped 삭제

- RelaxOn.xcodeproj/project.pbxproj
- RelaxOn/Assets.xcassets/Color.colorset/Contents.json
- RelaxOn/Assets.xcassets/Colors/Main Colors/Contents.json
- RelaxOn/Assets.xcassets/Colors/Main Colors/RelaxBlack.colorset/Contents.json
- RelaxOn/Assets.xcassets/Colors/Main Colors/RelaxDimPurple.colorset/Contents.json
- RelaxOn/Assets.xcassets/Colors/Main Colors/RelaxLavender.colorset/Contents.json
- RelaxOn/Assets.xcassets/Colors/Main Colors/RelaxNightBlue.colorset/Contents.json
- RelaxOn/Assets.xcassets/Colors/Main Colors/RelaxRealBlack.colorset/Contents.json
- RelaxOn/Assets.xcassets/Colors/System Colors/Contents.json
- RelaxOn/Assets.xcassets/Colors/System Colors/SystemGrey1.colorset/Contents.json
- RelaxOn/Assets.xcassets/Colors/System Colors/SystemGrey2.colorset/Contents.json
- RelaxOn/Assets.xcassets/Colors/System Colors/SystemGrey3.colorset/Contents.json
- RelaxOn/Utilities/Extension.swift
- Figma의 Design System 페이지에 정의된 색상들을 Color Asset으로 추가하였습니다
- Color extension을 사용해 `.relaxBlack` -> 이런 식으로 코드로 커스텀 색상을 사용할 수 있도록 하였습니다
- [피그마 색상 설정 관련 디스커션 링크](https://github.com/M1zz/RelaxOn/discussions/130#discussion-4272714)
- 커스텀 색상인 SystemGrey를 추가하다가 우연히 Xcode 자체에 SystemGray가 있다는 것을 알게 되어서, 관련 내용을 담은 [디스커션 링크](https://github.com/M1zz/RelaxOn/discussions/131#discussion-4272728)를 첨부합니다 
- 색상을 사용할 때 `Color.relaxBlack` 이렇게 사용할 수도 있지만, `.foregroundColor(.relaxBlack)` 과 같이 Color 타입이 확실한 경우에는 Color를 생략하고 사용하실 수 있습니다
- 현재 컬러 팔레트가 Main, System 두 파트로 나눠지는데 바로 색상에 접근할 지, 카테고리로 접근할 지를 고민한 [디스커션 링크](https://github.com/M1zz/RelaxOn/discussions/132#discussion-4272774)를 첨부합니다
- 과거 LullabyRecipe의 잔재로 예전에 사용했던 Color Asset이 남아 있는데, 과거 LullabyRecipe들의 View 들을 삭제할 때 잊지 말고 꼭 함께 삭제해야 할 것 같습니다
- Pull …
> [feat] #107 : Asset에 컬러 추가

- RelaxOn/Manager/UserDefaultsManager.swift
- RelaxOn/Model/DummyData.swift
- RelaxOn/Model/MixedSound.swift
- RelaxOn/Views/Kitchen/CDListView.swift
- RelaxOn/Views/Kitchen/CustomAlertView.swift
- CDLibrary에서 사용자의 music을 삭제할 수 있도록 구현 
- music의 id가 유일하다는 가정하에 로직이 동작함. 
- 기존 studioView에서 새로은 music을 생성시 id가 겹칠 수 있어서, id 생성 로직 변경
- edit 상태일 때는 CDListView 내부의 NavigationLink가 동작하지 않도록 설정
- preview에서 사용할 더미데이터 추가, 수정
https://user-images.githubusercontent.com/59302419/183242141-efbcaac2-356a-46c6-9fac-2e202e05fe70.mov
- @Minkyeong-Ko : CDListVIew를 수정함
- @M1zz @Kim-Yeon-ho  : id 생성 로직 변경함(studioView)
- @ccdkk : id 생성 로직 변경(remoteController에서 이전, 다음 곡 재생시 id를 기준으로 작동)
- font style 확정시 font 변경
- music 삭제하면 애니메이션으로 부드럽게 재배치 할 수 있도록 변경
- CDCardView() 밑에 붙어있는 .disabled().overlay().onTapGesture() modifier를 모듈화시키기
> [feat] CDLibrary에서 사용자의 music을 삭제할 수 있도록 구현

- RelaxOn.xcodeproj/project.pbxproj
- RelaxOn/Utilities/MultiPreview.swift
- RelaxOn/Views/Home/CdLibraryView.swift
- 기기 사이즈 호환, 다국어 지원이 잘 적용됐는지를 확인하기 위해서 preview에서 한번에 볼 수 있도록 MultiPreview를 구현
- 총 4가지 preview를 한번에 볼 수 있음
- 기존 preview 코드에 MultiPreview를 씌어주면 된다.
> [Feat] Preview 여러개 볼 수 있도록 구현

- RelaxOn/Views/Kitchen/SelectedImageView.swift
- RelaxOn/Views/Kitchen/StudioView.swift
스튜디오 뷰에서
- 재생이 되지 않는 음원들 해결
- 화이트노이즈의 볼륨이 잘 되지 않는 것을 해결
- 기존에 Sound의 displayName에 띄어쓰기가 들어가, 음원 파일을 찾지 못하였습니다. 따라서 띄어쓰기가 없는 imageName으로 AudioManager를 실행시켰습니다.
- 멜로디와 백색소음 위치가 바뀌면서, natural에서 whiteNoise로 변수명이 변경되면서, 에러가 있었습니다. 순서와 변수명을 수정하여 해결하였습니다.
Close #171
> [Feat] #171 스튜디오 뷰 내, 볼륨 조절 및 기타 에러 수정

- RelaxOn/Views/Home/CDCardView.swift
- RelaxOn/Views/Home/Music/NewMusicView.swift
- whiteNoise, melody, base 요소가 Empty로 설정되었을 때 "music"이미지 네임이 설정되는데 해당 경우에 music 이미지가 노출되는 현상을 수정하였습니다.
- 투명도 0.0을 줌으로써 해결했는데 empty인 경우 이미지를 주고싶지 않으면 어떻게 해야 할까요?
Close #197
> [Fix] empty Sound의 이미지 노출 수정

- RelaxOn/Views/Home/CdLibraryView.swift
- RelaxOn/Views/Home/Music/MusicViewModel.swift
- RelaxOn/Views/Home/Music/VolumeControlView.swift
- RelaxOn/Views/Onboarding/OnboardingView.swift
- 이번에도, Release 브랜치에서 에러가 발생해서, 에러를 급히 수정했습니다.
- NewMusicView에서 볼륨을 변경시에 화면이 팅기는 오류를 일단은 수정했으나, 값이 바로 반영되지 않습니다.
VolumeControllView에서
```
userRepositoriesState.remove(at: index ?? -1)
```
이 코드에서 에러가 발생합니다.
NewMusicView가 닫힐 때,
```
userRepositoriesState = userRepositories
```
로 값을 새로 주어도, 프린트 해보니, 변경된 볼륨값이 저장이 되지 않습니다.
현재 브랜치에서는, UserDefault에는 '볼륨이 변경된 값'이 저장되기 때문에
NewMusicView에서 앱을 재실행하면 그 볼륨값을 확인할 수 있지만,
새로고침되지 않아서, 뷰에서 변경한 볼륨값이 바로 반영되지 않습니다.
Close #208
> [fix] Release 브랜치 에러 및 MusicView에서 볼륨 변경시 닫히는 오류 해결

- RelaxOn/Model/MixedSound.swift
- RelaxOn/Views/Home/Music/VolumeControlView.swift
- coby가 올려주신 내용을 보고 commit을 되돌아보니 getUniqueID() func가 생기면서 MixedSound 의 init에 id가 사라졌는데 이 때문에 생기는 버그인 것 같습니다
- 볼륨 조절후 볼륨 잘 저장됩니다.
- 별개로 remove 되었다가 insert 되는 방식은 리팩토링되어야 할 것 같습니다. id를 넣어주면 NewMusicView가 왜 안 닫히는지는 의문입니다.🧐
Close #211
> [Bugfix] Volume Control시 NewMusicView가 꺼지는 현상 수정

- RelaxOn/Views/Kitchen/StudioView.swift
- StudioView에서 chevron에만 터치영역이 지정되어 있던 것을 "CD LIBRARY"까지 확대하였습니다.
Close #221
> [Fix] StudioView BackButton 터치영역 수정

- RelaxOn/Views/Kitchen/CDListView.swift
- CDLibraryView에서 편집시 원크기를 수정하였습니다.
- 기존에는 크기 값이 없어서, 피그마 값인 24로 변경하였습니다.
Close #220
> [fix] CDLibraryView에서 편집시 원크기 수정

- RelaxOn/Views/Home/CDCardView.swift
- RelaxOn/Views/Home/Music/NewMusicView.swift
- RelaxOn/Views/Kitchen/SelectedImageView.swift
- RelaxOn/Views/Kitchen/StudioView.swift
- RelaxOn/Views/Onboarding/OnboardingView.swift
- StudioView에서 선택한 이미지가 보여지지 않고 하나의 이미지만 보여주던 현상을 수정하였습니다.
- opacity가 없더라도 이미지가 잘 겹치기 때문에 이미지가 겹치는 뷰의 opacity를 제거하였습니다. StudioView에서는 opacity로 애니메이션을 주고 있어서 opacity를 제거하지않고 1.0으로 변경하였습니다.
- opacity를 제거하는 과정에서 EmptyView()를 사용하였는데, EmptyView()를 return하는 방법 말고, 아예 아무것도 return 하지 않는 방법이 있을까요?
Close #228
> [Fix] StudioView에서 선택한 이미지가 보여지지 않고 하나의 이미지만 보여주던 현상 & 이미지 겹치는 부분에 opacity제거

- RelaxOn/Views/Kitchen/StudioView.swift
- StudioView에서 음원 제작중 메인화면으로 돌아갔을 때 음원이 멈추도록 수정했습니다.
- 현재는 confirmationDialog 에서 최종적으로 메인화면으로 갔을 때 음원이 멈추게 해놨습니다.
- 추가적으로  StudioView에서 좌측상단의 backButton을 누른 후  confirmationDialog가 떳을때 음원이 멈추게 할지 여부를 정해야 할 것 같습니다.
Close #223
> [fix] CD제작중 메인화면으로 돌아갔을 때 음원이 멈추도록 수정

- RelaxOn/Views/Home/Music/MusicRenameView.swift
- RelaxOn/Views/Kitchen/StudioNamingView.swift
- RelaxOn/Views/Onboarding/OnboadingNamingView.swift
- 음원들의 이름을 설정 및 재설정 하는 뷰들의 UI를 수정했습니다.
- 데이크가 작업하신 MusicRenameView에 Localization이 적용되어있지않아 적용했습니다.
- 같은 기능을 하는 파일구조는 이슈를 생성해놓고 다음 스프린트때 작업하도록 하겠습니다.
Close #217 
<p align="left">
</p>
> [fix] MusicNaming 관련 뷰들 UI수정

- RelaxOn/Utilities/Static.swift
- RelaxOn/Views/Kitchen/CustomSegmentControlView.swift
- RelaxOn/Views/Kitchen/RectPreference.swift
- RelaxOn/Views/Onboarding/OnboardingView.swift
- CustomSegmentControl 코드를 수정했습니다.
- 현재 좌표이동값을 하드코딩한 느낌이 있는데, 같이 봐주시면 매우,,,감사드리겠습니다...
- 왼쪽 정렬에 맞추기 위해 Spacer를 사용해서 맞췄는데, 한국어일떄와 영어일때와 텍스트의 길이가 차이가 나서 다른 해결 방안이나 디자인적으로 얘기를 하면 좋을 것 같습니다.
- 한국어일떄 베이스에서 멜로디로 이동시 애니메이션이 적용되지 않는 버그도 보여 다음 스프린트때 추가 작업으로 생각됩니다.
- xSpace값이 참조를 여러번 하는 것 같아 값이 점점 작아지는 상황이 나와 현재는 해결하지 못하고 추후에 해결을 위해 주석으로 남겨뒀습니다. 다음 스프린트때 코드 수정이 필요해보입니다..!
Close #216
> [fix] 베이스, 멜로디, 백색소음 탭 좌우정렬

- RelaxOn/Views/Home/Music/NewMusicView.swift
이전에는 CD를 눌러도 위젯에 최근 재생 CD가 반영되지 않았고, 
play or pause 버튼을 눌러야지만 반영이 되었습니다.
MusicViewModel play() 함수에 widget에 데이터가 들어가는 부분을 넣어뒀는데  CD를 눌렀을 때는 반영이 안 되는 것을 보아
로직을 조금 고치면 어떨까 제안합니다...(지금은 임시로 같은 함수를 호출해놨습니다 ) MusicViewModel 과 NewMusicView 코드 짜신 분께 자세한 의논을 하고 싶습니다 슬랙으로 연락주세요 ~ !
Close #235
> [fix] CD를 클릭했을 때도 위젯에 재생된 CD data가 저장되도록 

- RelaxOn/Manager/AudioManager.swift
- RelaxOn/Views/Home/Music/MusicViewModel.swift
- material에서 base만 누르고 다른 것들은 '선택 안함'으로 눌렀을 때 옆 곡에 melody, whitenoise가 설정되어 있다면 모두설정된 곡을 playPause하고 base만 설정한 곡으로 넘어간 경우 melody, whitenoise가 플레이되던 현상 수정
-> 이전에 플레이되었던 음원이 audioMangaer()의 player에 그대로 남아있기 때문에 발생한 버그인 것 같습니다. 그래서 음원이 없다면 player에 nil을 할당해줬습니다.
- 저번에 수정했던 내용과 비슷한 버그인데 playPause를 눌렀을 시 또다시 발생하여 급히 픽스합니다.
- 비어있는 요소가 1개 일때는 크게 불편하지 않지만, 비어있는 요소가 2개인 곡에서 >>, <<를 이용하여 다음 곡으로 이동할 때 짧은 렉이 걸립니다. 원인은 아직 못찾았습니다.
Close #241
> [fix] material에서 base만 누르고 다른 것들은 '선택 안함'도 누르지 않고 바로 만든 경우 생기는 버그

- RelaxOn/Views/Kitchen/CDListView.swift
- StudioButton이 중앙의 + 버튼과 테두리를 클릭 했을시만 화면전환 되는 문제를 영역 전체를 클릭해도 넘어가도록 수정했습니다.
Close #268
> [feat] #268: Studio뷰로 넘어가는 뷰 수정

- RelaxOn/Model/Sound.swift
- Empty Sound 선택했을 때 나오는 이미지를 수정하였습니다.
- Sound가 Empty일때 ID를 통일하는건 어떨까요?
- Sound ID 정의에 대한 재설계가 필요해보입니다.
Close #236
> [refactor] #236 : Sound Empty 코드 개선

- RelaxOn/Views/Kitchen/CustomSegmentControlView.swift
- StudioView 및 OnboardingView에서 사용되는 SegmentControl의 하단 바 크기 수정 및 정렬을 수정했습니다.
- 좌측이 아이폰 14, 우측이 아이폰 SE3세대로 기기간 비율도 최대한 맞췄습니다.
Close #269 
<p align="left">
</p>
> [fix] #269 segmentControl 하단 바 크기 수정 및 정렬 수정

- RelaxOn/Views/Home/Music/MusicView.swift
- RelaxOn/Views/Kitchen/CDCoverImageView.swift
- RelaxOn/Views/Kitchen/StudioView.swift
- StudioView에서 CD Cover Image의 기본 Background 색상을 변경하였습니다.
- `addWhiteBackground()` 가 `addDefaultBackground()`로 변경되었습니다.
- Figma에서는 블러수치가 적용되어있지만, 블러 적용 시, 오히려 Figma와 다른 색상으로 표시되어 블러를 적용하지 않았습니다.
Close #280
**CD Image Cover만 봐주세요!**
변경 전
변경 후
> [Fix] #280 : CD 제작 시, CD Cover Image의 Background 색상 변경

- RelaxOn/Views/Home/Music/MusicView.swift
- RelaxOn/Views/Home/Music/VolumeControlView.swift
- volume이 조절되는 순간에 bool값을 줘서 조절중에는 애니메이션이 작동하지 않도록 하였습니다.
- 코드가 깔끔한 것 같지는 않아 추후에 리팩토링이 필요해 보입니다.
Close #300
> [fix] MusicView에서 볼륨을 조절할 때 의도하지 않은 애니메이션이 적용되던 현상 수정

- RelaxOn/Views/Kitchen/CDListView.swift
- CDLibrary에서 음원 delete시 delete 상태가 바로 적용되지 않던 현상 수정
Close #302
> [fix] CDLibrary에서 음원 delete시 delete 상태가 바로 적용되지 않던 현상 수정

- RelaxOn/Model/SoundType.swift
- RelaxOn/Views/Kitchen/CDListView.swift
- studio에서 슬라이더에 변화를 주지 않는 경우 defualt값인 50이 저장되어야 하는데 soundList의 default값인 0.8이 저장되는 현상을 수정 했습니다.
- 재생중인 노래가 삭제되었을 때 앱내컨트롤러에 해당 음원이 남아있고 음악이 계속 재생되는 현상이 있어서 이를 수정하였습니다.
- 야매 방식이라 추후 리팩토링이 필요해 보입니다. 볼륨 슬라이더에 변화가 없으면 저장되지 않는 현상에 대한 수정이 필요해 보입니다. @coby5502 아님 이대로 둬도 괜찮을까요?
Close #304 
Close #306
> [fix] studio에서 입력한 볼륨과 실제 생성된 볼륨이 다른 현상 & 앱내 컨트롤러 오류 수정

- RelaxOn/Views/Home/Music/MusicView.swift
- RelaxOn/Views/Home/Music/MusicViewModel.swift
- RelaxOn/Views/Kitchen/StudioView.swift
- 같은 음원에 앱내 컨트롤러 or 해당 음원 card 통해서 음원에 다시 들어갈때 노래가 재시작 되는 현상
- musicView에서 플레이중인 음악을 삭제했음에도 노래가 재생되고 앱내 컨트롤러에 해당 음악 정보가 남아있는 정보 수정 (mixedSound에 nil 대입)
Close #308  
Close #307
> [fix] musicView & 앱내 컨트롤러 오류 수정

- LockScreenWidgetExtension/LockScreenWidgetExtension.swift
- RelaxOn/Model/MixedSound.swift
- RelaxOn/Model/Sound.swift
- RelaxOn/Model/SoundType.swift
- RelaxOn/Views/Kitchen/SoundCardView.swift
- melody, whiteNois를 empty로 한 경우 .base 타입이 부여되었기 때문에 base의 음량을 조절해도 slider가 같이 움직이는 버그 해결
- 파라미터 추가
Close #310
> [fix] emptySoun를 .base 타입으로 생성하여 생기는 오류

- .github/workflows/ios.yml
- GitAction에서 실행되는 ios.yml 파일을 수정하였습니다.
- 주요변경 사항
- `steps`에`maxim-lobanov/setup-xcode@v1`를 추가하여, 빌드를 Xcode 14.0 에서 진행할 수 있도록 하였습니다. [fileChanged](https://github.com/M1zz/RelaxOn/pull/327/files#diff-fc40e39603744467ec4d9d7cb6c3bd67756ec09c037d03f3655904fc1c6bcfdaR17)
- 실행되는 Simulator의 iOS 버전을 iOS 16으로 수정하였습니다.  [fileChanged](https://github.com/M1zz/RelaxOn/pull/327/files#diff-fc40e39603744467ec4d9d7cb6c3bd67756ec09c037d03f3655904fc1c6bcfdaR34)
- `actions/checkout@v3`의 `name`이 사용되고 있지 않아 수정하였습니다.
- 현재 `main`과 `develop` 이름의 branch만 GitAction을 수행하도록 되어있습니다.
이를 매번 현재 작업이 진행중인 브랜치에서도 작동하도록 하는 것에 대해 여러분들의 의견이 궁금합니다.
Close #326
> [fix] #326 : Change Xcode Version in GitAction

- RelaxOn.xcodeproj/project.pbxproj
- RelaxOn/Model/MixedSound.swift
- RelaxOn/Model/Sound.swift
- RelaxOn/Model/SoundType.swift
- RelaxOn/Views/Home/Music/Component/MusicController.swift
- RelaxOn/Views/Kitchen/CDCoverImageView.swift
- RelaxOn/Views/Kitchen/RadioButtonGroupView.swift
- RelaxOn/Views/Kitchen/SoundCardView.swift
- RelaxOn/Views/Kitchen/StudioView.swift
- Sound의 ID가 Type에 따라 0~9, 10~19, 20~29의 범위 내에서 사용되도록 되어있었습니다.
해당 ID는 StudioView에서 ForEach에 사용될 ID를 위해 Sound에 `Identifiable`를 채택하면서 생긴 id 였고, 로직상 Type 끼리 ID의 충돌이 없는 상황이었습니다. 즉 각각의 Sound Type이 0부터 ID를 가져도 되는 상황이었습니다.
→ 각 Type마다 Sound 요소들의 ID가 0부터 [시작](https://github.com/M1zz/RelaxOn/pull/344/files#diff-a86337be06c289a0d5e295b8478833a81af84c95e7c99fffeb36e11b52bbc1b9R42)되도록 수정하였습니다. 
- ID가 수정됨에 따라 Empty Sound에 대한 정의를 수정해야했습니다.
→ 각 Type의 enum에 empty case를 넣어 Empty Sound가 ID 0을 가지도록 [수정](https://github.com/M1zz/RelaxOn/pull/344/files#diff-a86337be06c289a0d5e295b8478833a81af84c95e7c99fffeb36e11b52bbc1b9R25)하였습니다.
- Empty Sound 수정의 Side Effect
→ Empty Sound가 화면에서는 Empty라는 이름을 표시하되, fileName은 빈 문자열을 [사용](https://github.com/M1zz/RelaxOn/pull/344/files#diff-a86337be06c289a0d5e295b8478833a81af84c95e …
> [refact] #336 : Sound가 Empty인 로직 일부 수정

- RelaxOn.xcodeproj/project.pbxproj
- RelaxOn/Delegate/SoundProtocol.swift
- RelaxOn/Model/MixedSound.swift
- RelaxOn/Model/Sound.swift
- RelaxOn/Model/SoundType.swift
- RelaxOn/Views/Home/Music/Component/MusicController.swift
- RelaxOn/Views/Kitchen/CDCoverImageView.swift
- RelaxOn/Views/Kitchen/RadioButtonGroupView.swift
- RelaxOn/Views/Kitchen/SoundCardView.swift
- RelaxOn/Views/Kitchen/StudioView.swift
- Sound Type 별로 중복되는 코드를 줄이기 위해 [SoundProtocol](https://github.com/M1zz/RelaxOn/pull/346/files#diff-eea071c4031c8c33e0631891b922ad0dd3fac29886007426aa9a465f6d7b61bf)을 생성하였습니다.
- Sound Type 또는 Material이 추가되어도 `SoundType.swift` 파일 내에서 쉽게 반영할 수 있도록 하는 것이 목표였습니다.
- MixedSound이 Equatable protocol을 채택하기 위한 `==` 연산의 로직을 올바르게 [수정](https://github.com/M1zz/RelaxOn/pull/346/files#diff-6ae4c6b81c6634466a823aa94407136b6a1db3687bf3da25034d90e5b0441193R32)하였습니다.
- 작업을 끝내고 나니 왠지 오버 엔지니어링이었던 것같다는 생각이듭니다.ㅎㅎ
- Sound와 관련된 인스턴스가 생성되는 위치에 대한 고민이 있습니다. 커멘트 참고해주시면 감사합니다.[Sound](https://github.com/M1zz/RelaxOn/pull/346/files#diff-a86337be06c289a0d5e295b8478833a81af84c95e7c99fffeb36e11b52bbc1b9R15)
- #336
> [refact] : BaseSound, MelodySound, WhiteNoiseSound 구조를 수정합니다.

- RelaxOn.xcodeproj/project.pbxproj
- RelaxOn/App/RelaxOnApp.swift
- RelaxOn/App/Views/MainView.swift
- RelaxOn/App/Views/SecondView.swift
- RelaxOn/App/Views/SoundListView.swift
- RelaxOn/App/Views/SoundSaveView.swift
- RelaxOn/App/Views/SoundSelectView.swift
- RelaxOn/App/Views/ThirdView.swift
- RelaxOn/RelaxOn.entitlements
- MainView -> SecondView -> ThirdView로 화면 전환하는 구조를 만들었습니다.
- 식별가능한 이름으로 뷰 이름을 변경했습니다.
- ✅ Main View →  Sound List View
- ✅ Second View → Sound Select View
- ✅ Third View → Sound Save View
- 현재는 해결되었으나 동일한 오류가 날 수 있기 때문에 기록해두는 내용
- Second View -> Third View 화면 전환시
첫번째와 동일한 방식으로 내비게이션 링크에 fileInfo를 담아 보냈을 때,
Thired View가 아닌 Second View가 무한 반복 노출되는 오류가 있었습니다.
- Second View가 Main View에서 전달받은 fileInfo를 가공하지 않은 상태에서
Third View에 전달했기 때문에 났었던 오류로 추측하고 있으나 정확한 원인은 아직 파악하지 못했습니다.
> [BIBI] Navigation Stack 을 이용한 화면 전환 & Rename

- RelaxOn.xcodeproj/project.pbxproj
- RelaxOn/App/Manager/AudioManager.swift
- RelaxOn/App/Models/MixedSound.swift
- RelaxOn/App/Models/Sound.swift
- RelaxOn/App/Views/Create/SoundDetailView.swift
- RelaxOn/App/Views/Create/SoundListView.swift
- RelaxOn/App/Views/Create/SoundSaveView.swift
- SoundDetailView의 필요없는 재생, 정지 버튼 삭제
- SoundDetailView onAppear 시 배경음악 자동으로 반복 재생 기능 추가
- SoundDetailView onDisappear 시 배경음악 자동으로 종료 기능 추가
- Model객체는 MixedSound.swift 파일만 수정했습니다
- AudioManager.swift 파일 추가했습니다
- Volume을 View의 변수로 따로 할당하지 않고 AudioManager만을 이용해 업데이트를 하고 싶었으나 실패했습니다
- 시도해 봤던 subscript 함수는 아래와 같습니다
```swift
subscript<T>(dynamicMember keyPath: WritableKeyPath<AVAudioPlayer, T>) -> T? {
get {
audioPlayer?[keyPath: keyPath]
}
set {
audioPlayer?[keyPath: keyPath] = newValue
}
}
```
- 다른 좋은 방법이 있다면 추천해주세요!
> ✨[Feat]: Play & Pause Sound Auto

- RelaxOn.xcodeproj/project.pbxproj
- RelaxOn/App/Extensions/UserDefaults+Extension.swift
- RelaxOn/App/Manager/AudioManager.swift
- RelaxOn/App/Manager/UserDefaultsManager.swift
- RelaxOn/App/Manager/UserFileManager.swift
- RelaxOn/App/Models/MixedSound.swift
- RelaxOn/App/Models/Sound.swift
- RelaxOn/App/RelaxOnApp.swift
- RelaxOn/App/Utils/Errors.swift
- RelaxOn/App/ViewModel/AppState.swift
- RelaxOn/App/ViewModel/MixedSoundsViewModel.swift
- RelaxOn/App/Views/Create/SoundDetailView.swift
- RelaxOn/App/Views/Create/SoundListView.swift
- RelaxOn/App/Views/Create/SoundSaveView.swift
- RelaxOn/App/Views/Listen/ListenListView.swift
- RelaxOn/App/Views/MainTabView.swift
- init 할 때 `id` 를 `UUID`생성하는 것으로 수정했습니다.
```swift
struct MixedSound: Hashable, Codable {
let id: UUID            // 생성된 MixedSound의 고유 아이디
var fileName: String    // Original Sound의 fileName
var volume: Float       // 저장할 볼륨 값
var imageName: String   // 저장할 이미지
init(fileName: String, volume: Float = 0.5, imageName: String = recipeRandomName.randomElement()!) {
self.id = UUID()
self.fileName = fileName
self.volume = volume
self.imageName = imageName
}
}
```
현재 코드 기준 사용법은 아래 예시와 같습니다.
앱의 문서 디렉터리에 `MixedSound` 객체를 저장하려면:
```swift
let mixedSound = MixedSound(id: UUID(), name: "예제 사운드")
do {
try UserFileManager.shared.saveMixedSound(mixedSound)
} catch {
print("믹스된 사운드 저장 오류: \(error.localizedDescription)")
}
앱의 문서 디렉터리에서 MixedSound 객체를 삭제하려면:
```swift
let mixedSoundToDelete = MixedSound(id: …
> ✨[Feat]: Save & Load MixedSound

- RelaxOn/App/Views/Create/SoundDetailView.swift
- 사운드의 음향, 음정 등을 수정할 기능의 UI를 작업하였습니다!
- PR기준으로 3가지를 수정하는 버튼을 만들었습니다!
- 이는 추가적으로 만들 수 있습니다!
- 반복적인 코드를 어떻게하면 가독성 있고 효율적으로 쓸 수 있을지 고민했습니다!
- 그래서 원하는 원의 크기를 입력하면 그 크기만큼 원이 생기고 슬라이더 버튼은 그 크기의 1/2 해서 원 위에 위치하게 했습니다!
- 현재 슬라이더의 움직임이 부자연스러운 것이 있으나 이는 추후에 수정예정입니다!
> 🎨[Design]: SoundDetailView UI

- RelaxOn/App/Views/Create/SoundDetailView.swift
- RelaxOn/App/Views/Create/SoundSaveView.swift
- Figma 파일 기준으로 기존의 UI를 수정하였습니다!
- 선택한 사운드 이름이 상단에 표시
- 사진에 굴곡 추가
- Cancel, Save를 버튼 이미지와 저장으로 변경
- 각 UI에 마다 Frame을 씌워서 위치를 정렬하였으나 이는 iPhone14 Pro 기준임
> 🎨[Design]: SoundSaveView UI

- RelaxOn.xcodeproj/project.pbxproj
- RelaxOn/App/Views/Relax/RelaxView.swift
- RelaxOn/App/Views/Relax/TimerProgressView.swift
- RelaxView에서 시간을 선택하고 실행해도 타이머가 실행되지 않는 버그를 발견하여 수정
- Print문을 통해서 데이터 유실이 이루어지는 부분이 어디인지 파악
- 시간선택하고 Start를 누른 시점과 TimerProgressView가 시작된 시점
- TimerProgressView에서 유실됨을 확인
- 각 뷰의 ObservedObject 인스턴스 값이 다름
- Time이라는 하나의 클래스를 관찰하는 ObservedObject이지만 각각 다른 인스턴스를 가지고 있었음.
- 하나의 클래스를 관찰하는 인스턴스라도 각 인스턴스는 독립성을 지닌 객체로써 서로 다른 값을 가질 확률이 있음
- 그렇기 때문에 RelaxView에서 변경된 값을 2번 뷰에서도 업데이트할려면 해당 인스턴스를 공유해야하는데 
다른 인스턴스를 가지고 있었기에 다른 값을 가지고있었다고 생각함
- RelaxView에서 생성한 ObservedObject 인스턴스를 TimerProgressView에 전달하여 동일한 인스턴스로 Time에 접근
- 급한 내용이라 생각하여 해당 이슈만 해결하고 PR 요청합니다
- Close #380
> 🐛[Fix]: Timer 실행 오류

- RelaxOn.xcodeproj/project.pbxproj
- RelaxOn/App/ViewModel/CustomSoundViewModel.swift
- RelaxOn/App/Views/Components/DragCircularSlider.swift
- RelaxOn/App/Views/Components/SnapCircularSlider.swift
- RelaxOn/App/Views/Home/SoundDetailView.swift
- Drag : 볼륨, 주기, 음높이 조절
- Snap : 필터 전환
- 코드를 살펴본 결과 Filter기능에는 Range의 개념이 없으므로 이를 삭제하였습니다.
- 기존 로직은 이동할 때마다 currnetFilterIndex에 +1을 하여 필터를 교체하였습니다.
- 슬라이더의 위치에 따라 0~4의 값을 가지는 snappedAngle를 currentFiterIndex에 대입하여 필터를 교체합니다.
- 즉, 슬라이더의 위치에 따라서 해당 필터가 재생되게끔 구현하였습니다.
- 12시 방향에서 좌우 이동하면 슬라이더가 전체회전을 하는 현상이 있었으나 이를 개선하였습니다.
- 필터에 대한 로직을 수정하기 전에 앱이 꺼지는 현상이 있었는데 수정 후 해당 현상이 사라졌습니다.
- 추가적으로 불필요한 코드를 확인하여 삭제, 수정하였습니다.
- 필터를 전환하는 기능은 정상 작동합니다!
> 🐛 [Fix]: CircularSlider 분리 & FilterSlider 애니메이션 보완

- RelaxOn/App/Views/Components/DragCircularSlider.swift
- RelaxOn/App/Views/Components/SnapCircularSlider.swift
- SoundDetailView 내의 지표들의 위치를 고정하였습니다.
- Double.random(in:...) 사용해 화면이 나올 때마다 위치가 랜덤으로 지정되었으나 이를 0으로 고정시킴으로써
지표들의 위치는 매번 똑같이 표시됩니다.
- 지표들의 위치가 다른 것은 각 지표가 가진 범위값이 다르기 때문입니다. 
따라서 모든 지표의 위치값은 0이지만 각 범위마다 0의 위치가 다르기에 이와 같이 표시됩니다.
- 지표의 위치를 정렬시킬까 고민하다가 오히려 지금과 같은 위치가 사용자가 움직이고 싶게 만들 것 같아서 
PM(승우님)과 소통 후 작업 마무리 하였습니다.
Close #444
> 🐛[Fix]: SoundDetail뷰의 지표 위치 고정

- RelaxOn/App/Manager/TimerManager.swift
- RelaxOn/App/Views/Timer/TimerProgressView.swift
- 타이머를 실행하고 화면이동하면 타이머가 리셋되는 현상을 수정하였습니다. 
- onAppear과 onDisappear의 적용 시킬 때 사용자의 행동을 예측하지 않아 
화면의 변화에 따라서 Timer가 작동했었습니다.
화면이 사라짐이 곧 타이머의 종료와 연관되어 있지 않으므로 Action을 비웠습니다.
그리고 onDisappear을 아예 삭제해버리니 앱이 꺼지는 현상이 있었습니다.
이는 제가 이해한 바에 따르면 화면이 사라졌을 때의 조건이 사라짐으로 메모리 누수현상을 방지하고자 Xcode가 
앱을 중단시키지 않았나 생각합니다.
화면이 표시될 때마다 startTimer를 실행함으로써 Timer인스턴스가 중복됨을 확인했습니다.(시간이 2초씩 감소)
그래서 remainingSeconds를 활용하여 타이머가 비활성화임을 확인하고 startTimer함수를 호출하게 수정하였습니다.
```Thread 1: EXC_BREAKPOINT (code=1, subcode=0x10a65c2cc)```
- 전반적으로 타이머 관련 코드들의 정리가 필요해보입니다. 이는 추후에 보완해보겠습니다.
Close #446
> 🐛[Fix]: #446-타이머 리셋 이슈

- RelaxOn/App/Views/Timer/TimerSoundSelectModalView.swift
* 모달 뷰에서 소리를 선택하고 완료를 누르면 소리가 자동 재생된다.
* 저장된 소리가 없어도 모달 뷰에서 완료를 누르면 소리가 자동 재생된다.(WaterDrop 재생됨)
- TimerSoundSelectModalView에서 완료버튼 조건문을 수정
- 모달뷰의 완료버튼을 누르면 재생하는 메서드가 실행됨
- TimerMainView에서 Start버튼을 누르면 play 메서드가 작동하기 때문에
중복되는 코드 & 불필요한 작동 으로 판단하여 삭제
- 해당 코드를 삭제하면 오류가 해결되는 것처럼 보이는데 코드 작성자(비비)의 의도를 모르는 상태에서 수정하면
추후에 또 다른 오류를 불러일으키진 않을지 고민을 해봤습니다.
- 비비와 소통 후 어떤 상황에 대응하기 위한 의도를 파악하고 오류를 불러일으킬 소지가 없을 것 같다는 판단 하에
PR을 작성하였습니다.
Close #457
> 🐛 [Fix]:  소리 선택창에서 자동재생되는 오류

- RelaxOn/App/Views/Listen/ListenListCell.swift
offset으로 Uderline 위치 하단으로 이동시켰습니다.
```swift
// 전
Rectangle()
.frame(height: 1)
.foregroundColor(Color(.ListenListCellUnderLine))
.padding(.vertical, 2)
.background(Color(.DefaultBackground))
```
```swift
// 후
Rectangle()
.frame(height: 1)
.foregroundColor(Color(.ListenListCellUnderLine))
.padding(.vertical, 2)
.background(Color(.DefaultBackground))
.offset(y: 12) // 추가
```
> 현재 List 를 이용했기 때문에 onDelete로 자동생성되는 삭제버튼을 커스텀하기 어려워 필요하다면 다음 디자인 개선때에는 List를 커스텀 버티컬 스크롤뷰로 구성하면 좋겠다는 생각을 했습니다.
- 이슈로 등록할 정도는 아니라고 판단하여 따로 생성하진 않았습니다.
> 🎨[Design]: Cell Underline 위치 수정

- RelaxOn/App/Views/Components/SearchBar.swift
- `as-is` 저장한 나만의 소리를 검색해보세요 -> 한번 누르면 문구만 사라지고 키보드가 올라오지 않음 -> 한번더 누르면 키보드가 올라옴
- `to-be` 한번 눌렀을 때 바로 키보드 올라오기
```swift
TextField("저장한 나만의 소리를 검색해보세요", text: $text)
.autocorrectionDisabled(true)
.foregroundColor(Color(.SearchBarText))
```
이 코드는 SwiftUI에서 TextField를 정의하고 있으며, text 라는 @Binding 변수와 함께 사용됩니다. 터치가 발생하면 플레이스홀더가 사라지고 키보드가 올라오게 됩니다. `.autocorrectionDisabled(true)`를 사용하여 자동 완성 기능을 비활성화했습니다.
---
- `as-is` 아무 내용도 입력하지 않고 검색창 return 하면 문구 사라진 채로 검색 바 유지됨
- `to-be` 아무 내용도 입력하지 않고 검색창 return 하면 “저장한 나만의 소리를 검색해보세요” 문구 재활성화
```swift
Image(systemName: "xmark.circle.fill")
.padding()
.offset(x: 10)
.foregroundColor(Color(.SearchBarText))
.opacity(text.isEmpty ? 0.0 : 1.0)
.onTapGesture {
text = ""
UIApplication.shared.endEditing()
}
```
이 코드는 텍스트 필드에 입력된 텍스트가 있을 경우 스택 뷰에서 오버레이 되는 …
> 🐛 [Fix]: 검색 기능 수정
