M1zz/RelaxOn

- LullabyRecipe/Views/Home/Music/Music.swift
플레이 버튼
- radius 값: 12 → 17
- font size: → 16
추가로 여백 조정했습니다.
> Change play button

- LullabyRecipe/Model/Sound.swift
- LullabyRecipe/Views/Home/MixedSoundCard.swift
- LullabyRecipe/Views/Home/Music/Music.swift
- LullabyRecipe/Views/Home/Music/MusicViewModel.swift
- LullabyRecipe/Views/Home/Music/VolumeControl.swift
- _~~MusicView에 @State 변수인 `newData`를 만들어서 `VolumeControl` 에서 Binding 하고 변화된 볼륨 값을 적용하려고 시도하였습니다~~_
- `MusicView` 볼륨 변경 후 save 버튼을 누르면 볼륨이 곧바로 적용되도록 수정하였습니다
- _~~`MusicView` 에서 `newData`라는 Struct 값을 바뀐 볼륨이 적용된 `newMixedSound` 값으로 대체하고 싶었는데 실패하였습니다~~_
- _~~그래서 `MixedSound` 구조체 안에 mutating 함수로 볼륨 값을 업데이트 하는 것도 시도해 보았는데, `VolumeControl` 뷰로 돌아와서 다시 `newData`를 확인해 보면 이전 값 그대로를 유지하고 있습니다~~_
- `MixedSound`를 struct에서 class로 변경해 변경된 볼륨을 적용할 수 있도록 바꾸었습니다
- _~~`newData`를 `newMixedSound` 값으로 업데이트 하려면 어떻게 해야 할까요?~~_
- _~~아니면 애초에 `MusicView`에서 `VolumeControl`로 값을 넘겨주는 과정이 잘못된 것인지 궁금합니다~~_
- `MixedSound`를 struct에서 class로 변경하였을 때 생기는 문제가 혹시 있을까요?
> feat: 볼륨 조절 후 Save 버튼 누르면 바로 적용

- LullabyRecipe.xcodeproj/xcuserdata/kim-yeonho.xcuserdatad/xcschemes/xcschememanagement.plist
> feat : backgroundRemove

- .gitignore
> [docs] : Update .gitignore

- .github/ISSUE_TEMPLATE/fix-issue-template.yml
---
name: Pull Request Tamplate
about: PR 템플릿
title: "[fix] PR Title"
labels: ['fix']
---
Close #31
- fix issue templete 이용시 label이 인식되도록 변경했습니다.
- templete 내용에 Current State 가 2개 중 하단을 After State로 변경해서 혼돈이 없게 합니다.
> [fix]: #31 fix issue templete 수정

- .github/ISSUE_TEMPLATE/feature-issue-template.yml
- .github/PULL_REQUEST_TEMPLATE.md
Close #35 
Pull Request Template 속성 제거
> [Fix] #35 : Pull Request Template 수정

- LullabyRecipe.xcodeproj/project.pbxproj
- LullabyRecipe/Model/Sound.swift
1) realse에서도 #34와 똑같은 문제가 발생합니다. MixedSound.swift 파일에 있는 것을 두고, 다른 곳에서 재선언된 MixedSound를 삭제했습니다
2) [CustomTabView 파일 경로 못찾는 문제](https://rriver2.notion.site/bfd8aab7c15e4d778e1ad4793ed5d428)를 해결했습니다.
- 다음 리팩토링을 위해 머지가 빨리 되었으면 합니다
- 이번에 둘 중 하나라도 해결을 하지 않으면 빌드에러가 발생해서 두 개의 이슈를 같이 해결해서 PR을 날렸는데 이런 상황에서도 두개의 issue를 나눠서 PR을 날려야 하는지 궁금합니다.
Close #66
Close #68
> [fix] #66 Sound에 존재하는 MixedSound 제거 

- README.md
- Refactoring Template 깃 경로를 dev로 잘못 설정하여 main으로 수정하여 다시 작업해서 올렸습니다.
- 전에 review받았던 수정사항들은 다 반영이 되었고 원본repo와 차이를 맞추기 위해 READ.md를 수정하였습니다.
- #60 Refactoring Template 추가 작업
Close #60
> [docs]: Refactoring Template 깃 경로 설정 변경 및 추가 작업

- LullabyRecipe/Manager/AudioManager.swift
AudioManager class에서 사용하지 않는 static let shared = AudioManager() 코드 존재
Close #63
> [Fix]: #63 shared 삭제

- LullabyRecipe/Manager/AudioManager.swift
> [Fix]: #73 함수 래핑

- .github/workflows/ios.yml
- Git Action File 추가
- main와 develop 브랜치에 대해서 적용
- Push, PR로 Merge가 될 경우, 빌드 여부를 테스트합니다.
Close #79
>  [docs] #79 : Create Git Action File

- RelaxOn/Manager/AudioManager.swift
- 무음 모드에서도, 음원 재생 소리가 들리도록 하였습니다.
Close #126
> [Feature]: #126 무음 모드에서 소리 재생

- RelaxOn/Views/Kitchen/StudioView.swift
- StudioView에서 음원 볼륨 저장이 안된 채로 음악이 생성되는 오류를 고쳤습니다.
- StudioView에서 Slider의 검정 배경을 지웠습니다.
Close #201
> [Feat] StudioView에서 음원 볼륨 저장

- RelaxOn/Views/Home/Music/NewMusicView.swift
- 새로생긴 newMusicView에서 타이머가 종료되면 음악이 종료될 수 있도록 수정했습니다.
> [Feat] 타이머 종료되면 음악 종료되도록 수정

- RelaxOn/Views/Home/Music/MusicViewModel.swift
- albumCover 안뜨는 현상 수정
- remoteController albumcover에 들어가는 타입으 UIImage라 세개가 겹쳐 있는 이미지가 없는한 똑같은 albumcover를 올릴수가 없습니다.. 그래서 지금은 임시로 base 이미지를 올려놓기로 했습니다. 추후에 모든 이미지가 올라오면 그때 수정해야할 것 같습니다.
Close #213
> [fix] albumCover 안뜨는 현상 수정

- RelaxOn/Views/Home/CdLibraryView.swift
- RelaxOn/Views/Home/Music/NewMusicView.swift
- remoteController에 데이터를 넣어주는 것을 end하는 함수를 추가했고 begin하는 시기를 수정하였습니다.
Close #215
> [fix] remoteController가 onboarding, kitchen music에 반응하지 않도록 설정

- RelaxOn/Views/Home/Music/MusicRenameView.swift
- RelaxOn/Views/Kitchen/StudioNamingView.swift
- RelaxOn/Views/Onboarding/OnboadingNamingView.swift
- 버튼이 UI상 비활성화인데 작동되는 문제를 해결하였습니다.
Close #222
> [fix] : 버튼 비활성화 문제 해결

- RelaxOn/Views/Home/Music/MusicView.swift
- 하단에 볼륨을 조절할 때, 하단바와 겹치는 경우가 잦아, 간격을 조정하였습니다.
Close #265
> [feat] 음악 재생화면 디자인 수정

- RelaxOn/Views/Kitchen/CDNamingView.swift
- 영문자판만 가능하던 키보드를 수정하였습니다.
Close #277
> [fix]: #277 영문키보드만 가능하던 부분 수정

- RelaxOn/Views/Kitchen/CDNamingView.swift
- CDNamingViewdml 중복 코드를 삭제하였습니다.
- Merge 과정에서 실수가 발생했습니다. 주의하겠습니다.😓
X
X
> [Fix] #283: CDNamingView에서 UI가 중복되어 표시되는 현상

- RelaxOn/Views/Home/Timer/TimerSettingView.swift
> [fix] 타이머 시간 피커 배경화면 변경

- RelaxOn/Manager/TimerManager.swift
- RelaxOn/Views/Home/Timer/TimerSettingView.swift
> [feat] 타이머 cancel 기능 추가

- RelaxOn/Views/Home/Timer/TimerSettingView.swift
- 타이머가 cancel 되었을 때 lockScreenWidget에 0의 값을 주어 초기화 합니다.
Close #296
> [feat] 타이머 캔슬시 락스크린 초기화

- RelaxOn/Model/SoundType.swift
- BaseSound, MelodySound, WhiteNoiseSound 의 sounList의 soundType 이 모두 베이스로 저장되서 발생하는 현상이었습니다. 각각 수정해 주었습니다.
Close #이슈넘버
> [fix] 뮤직뷰에서 볼륨이 한 번에 조절되는 현상 수정

- .swiftlint.yml
- RelaxOn.xcodeproj/project.pbxproj
- RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch (Complication).xcscheme
- RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch (Notification).xcscheme
- RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch.xcscheme
- SwiftLint 파일이 iOS App을 제외한 모든 Target에 적용되는지 확인하지 못했습니다.
Close #312
> [feat] #312 : SwiftLint 적용 및 파일 추가

- .swiftlint.yml
- RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch (Complication).xcscheme
- RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch (Notification).xcscheme
- RelaxOn.xcodeproj/xcshareddata/xcschemes/RelaxOnWatch.xcscheme
- RelaxOn/Manager/WidgetManager.swift
- RelaxOn/Utilities/Static.swift
- RelaxOn/Utilities/ViewModifiers.swift
- RelaxOn/Views/Home/Music/CDLibraryMusicController.swift
- RelaxOn/Views/Home/Music/MusicView.swift
- RelaxOn/Views/Home/Music/MusicViewModel.swift
- RelaxOn/Views/Home/Timer/TimerSettingView.swift
- RelaxOn/Views/Kitchen/CDNamingView.swift
- RelaxOn/Views/Kitchen/CustomSegmentControlView.swift
- RelaxOn/Views/Kitchen/RadioButtonGroupView.swift
- RelaxOn/Views/Kitchen/SoundCardView.swift
- RelaxOn/Views/Kitchen/StudioView.swift
- RelaxOn/Views/Onboarding/OnboardingFinishView.swift
- RelaxOnWidget/CDWidgetEntry.swift
- RelaxOnWidget/RelaxOnWidget.swift
- 모두 같은 상태일 거라 짐작해서 swiftLint 워닝을 완화 및 코드 수정을 했습니다.
- viewModifier나 view extension인 경우에만 identifier_name을 예외 처리 하고 싶은데 마땅한 방법을 모르겠어서..identifier_name을 다 예외 처리 했습니다..아시는 분 있으면 코멘트 부탁드립니다.
- function_parameter_count는 widgetManager 수정 후 기존 대로 warning: 5, error: 6로 변경해 두겠습니다.
Close #314
> [fix] swiftLint 에러 수정

- RelaxOn/Views/Kitchen/StudioView.swift
- RelaxOn/Views/Kitchen/VolumeSlider.swift
- 온보딩뷰와 스튜디오뷰에서 음원 선택시 이전 선택 음원이 꺼지는 현상을 수정했습니다.
Close #이슈넘버
#337
> [refactor] #337 : 음악 믹싱시 음원 종료 안되게 수정

- RelaxOn/Views/Kitchen/CDNamingView.swift
- CD 이름 변경시 이제 한영 자판이 올라옵니다.
Close #338
> [Fix]: 키보드 한영 가능하게 

- RelaxOn/App/Views/Create/SoundDetailView.swift
- RelaxOn/App/Views/Create/SoundSaveView.swift
- SoundSaveView UI 작업 완성
- UI 기준작업이라 기능적인 부분은 구현이 되어있지 않습니다!
- 추가예정기능) 저장, 닫기, 이미지 랜덤변경 
- 키보드가 올라오면 화면도 같이 올라가는 현상이 있습니다. 추후 Fix 하겠습니다.
- SoundDetailView 코드에서 .sheet를 .fullScreenCover로 변경하였습니다.
> [Design]: 임시 SoundSaveView UI 완성 

- RelaxOn/App/Views/Listen/ListenListView.swift
- Listen List View UI 작업 완료했습니다.
- Model 없이 UI만 구현했습니다.
- 추후 Data Flow 정리 후 기능까지 구현하겠습니다.
왼쪽 : Figma, 오른쪽 : 구현한 화면
상세한 부분은 조금 달라보이는데 피드백 주시면 고치겠습니다!
<p><img width="500" alt="backlog" src="https://user-images.githubusercontent.com/108422901/227395265-eb6c583f-d094-4573-970f-a25a020c5adf.png">
> 🎨[Design]: Set ListenListView UI

- RelaxOn/App/Views/Listen/ListenListView.swift
- 업데이트된 Figma 파일 기준으로 작업하였습니다!
- 단순 UI 작업
> 🎨 [Design]: Update ListenListView UI

- RelaxOn.xcodeproj/project.pbxproj
- RelaxOn/App/Models/Time.swift
- RelaxOn/App/Models/Times.swift
- RelaxOn/App/Views/Relax/RelaxView.swift
- RelaxOn/App/Views/Relax/TimerProgressView.swift
- 타이머 뷰와 타이머가 실행되는 뷰를 만들었습니다!
- 단순 UI 작업
- 최근 머지 중 주요한 코드와 컨플릭트가 나서 머지가 된 시점에서 분기하여 코드를 입혔습니다
> 🎨[Design]: TimerView & TimerProgressView UI

- RelaxOn/App/Views/Create/SoundDetailView.swift
- SoundDetailView UI 작업
- 가운데에 원을 하나 추가하였습니다!
- 슬라이더 버튼의 위치를 랜덤으로 변경하였습니다!
- Close #373
> 🐛[Fix]: CircleSlider UI

- RelaxOn/App/Views/Listen/ListenListView.swift
- RelaxOn/App/Views/Relax/RelaxView.swift
- ListenListView 안의 텍스트를 변경했습니다!
- search -> 나만의 소리를 검색해보세요
- RelaxView 안의 텍스트를 변경했습니다!
- 당신의 소리를 선택해주세요 -> 나만의 소리를 선택해주세요
- 단순 UI 작업입니다!
| ListenListView | RelaxView |
| --- | --- |
| <img width="249" alt="image" src="https://user-images.githubusercontent.com/109560875/236175641-8c0adc6e-f49a-4840-b93c-509aabf68142.png"> | <img width="249" alt="image" src="https://user-images.githubusercontent.com/109560875/236175487-102d0803-f394-4eb7-b80f-a45786f8da0e.png"> |
> 🐛[Fix]: Text Change

- RelaxOn/App/Manager/AudioEngineManager.swift
- RelaxOn/App/ViewModel/CustomSoundViewModel.swift
- RelaxOn/App/Views/Components/CircularSlider.swift
- RelaxOn/App/Views/Home/SoundDetailView.swift
- SoundDetailView의 CircleSlider 기능을 일부 구현했습니다.(필터 제외)
- Pitch : 음정 조절 기능 (현재 4옥타브 조절 가능)
- Volume : 소리 크기 조절 기능 (0 ~ 1까지 조절 가능)
- Interval : 소리 길이 조절 기능 (1초의 오디오가 조금 길어짐)
- 필터 기능은 추후 구현예정이며 다음 스프린트 내용에 따라서 UI도 추가 작업 예상됩니다!
- 기능은 작동하지만 정확한 계산식, 로직은 수정이 필요합니다!
- Close #387
> ✨ [Feat]: #387 Feature-Custom Sound(Pitch, Volume, Interval)

- RelaxOn/App/Manager/AudioEngineManager.swift
- RelaxOn/App/Models/CustomSound.swift
- RelaxOn/App/ViewModel/CustomSoundViewModel.swift
- RelaxOn/App/Views/Components/CircularSlider.swift
- RelaxOn/App/Views/Home/SoundDetailView.swift
> ✨[Feat]: 오디오 필터 변경 기능

- RelaxOn/App/Extensions/FileManager+Extension.swift
- RelaxOn/App/ViewModel/CustomSoundViewModel.swift
- RelaxOn/App/Views/Home/SoundDetailView.swift
- RelaxOn/App/Views/Home/SoundSaveView.swift
- RelaxOn/App/Views/Listen/ListenListCell.swift
- 유저가 컬러를 변경하지 않으면 default 컬러가,
변경하면 변경된 값이 String 형태로 JSON 파일에 저장됩니다.
> ✨[Feat]: 유저가 변경한 Color 값 저장 & 불러오기

- RelaxOn.xcodeproj/project.pbxproj
- RelaxOn/App/Utils/Common.swift
- RelaxOn/App/Views/Components/CircularSlider.swift
- RelaxOn/App/Views/Home/SoundDetailView.swift
circleWidth가 array로 되어있어서, 그리고 인덱스로 접근하고 있어서, 0, 1, 2의 의미를 알 수 없어서 수정했습니다!
Close #이슈넘버
> ♻️[Refactor]: width가 array로 되어있는 것을 enum으로 변경

- RelaxOn/App/Assets/RenewAssets.xcassets/DetailViewColorSet/CircularSliderBackground.colorset/Contents.json
- RelaxOn/App/Assets/RenewAssets.xcassets/DetailViewColorSet/CircularSliderLine.colorset/Contents.json
- RelaxOn/App/Assets/RenewAssets.xcassets/DetailViewColorSet/Contents.json
- RelaxOn/App/Extensions/Color+Extension.swift
- RelaxOn/App/Views/Home/SoundDetailView.swift
- DetailView CircularSlider 색상이 레거시 코드 중 `RelaxDimPurple` 컬러로 설정된 것 확인
- 색상 2개 추가하고 변경했습니다.
> 🎨[Design]: DetailView Color 수정

- RelaxOn/App/Views/Home/SoundSaveView.swift
- 저장 버튼 눌렀을 때 title.count 체크하여 0이하이면 aleart 창이 표시됩니다.
```swift
Button {
if title.count <= 0 {
alertMessage = "한 글자 이상 입력하세요."
isShowingAlert = true
} else {
let success = viewModel.save(
with: originalSound,
filter: viewModel.sound.filter,
title: title,
color: viewModel.color)
if success {
presentationMode.wrappedValue.dismiss()
presentationMode.wrappedValue.dismiss()
appState.moveToTab(.listen)
} else {
alertMessage = "동일한 파일명이 존재합니다.\n다른 파일이름으로 시도해보세요."
isShowingAlert = true
}
}
} label: {
Text("저장")
.foregroundColor(Color(.PrimaryPurple))
}
```
> ✨[Feat]: Save시 파일명 Validation Check

- RelaxOn.xcodeproj/project.pbxproj
- RelaxOn/App/Manager/AudioEngineManager.swift
- RelaxOn/App/ViewModel/AppState.swift
- RelaxOn/App/ViewModel/CustomSoundViewModel.swift
- RelaxOn/App/Views/Components/CircularSlider.swift
- RelaxOn/App/Views/Home/SoundDetailView.swift
- RelaxOn/App/Views/Home/SoundListView.swift
- RelaxOn/App/Views/Listen/ListenListView.swift
- RelaxOn/App/Views/MainTabView.swift
- RelaxOn/App/Views/Onboarding/TutorialView.swift
isFirstVisit일 때 SoundListView에 navigationDestination을 이용
```swift
.navigationDestination(
isPresented: $appState.showSoundDetail) {
SoundDetailView(
isTutorial: false,
originalSound: OriginalSound(name: "물방울", filter: .WaterDrop, category: .WaterDrop))
}
```
온보딩과 튜토리얼이 종료되면 SoundDetailView로 바로 이동하도록 수정
ListenListView 의 cell을 터치하면 애니메이션과 함께 보여짐
```swift
if isShowingPlayer {
Button {
isShowingSheet = true
} label: {
SoundPlayerBottomView()
}
.sheet(isPresented: $isShowingSheet, onDismiss: {
isShowingSheet = false
}) {
SoundPlayerFullModalView()
}
.animation(
.easeInOut(duration: 1)
.repeatForever(autoreverses: false),
value: 1.0
)
}
```
기존 `scheduleNextBuffer()` 에서 `player.isPlaying`을 체크하던 로직 제거
```swift
private func scheduleNextBuffer() {
print(#function)
guard let buffer = audioBuffer …
```
> 튜토리얼 로직, 하단 플레이어 로직 변경, 자동재생, interval 적용되지 않는 문제 #420 #428
